# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import rc_polar_icon


class Ui_PolarGraphs(object):
    def setupUi(self, PolarGraphs):
        PolarGraphs.setObjectName("PolarGraphs")
        PolarGraphs.resize(845, 567)
        PolarGraphs.setStyleSheet("background-color:#e9e9e9;")
        self.centralwidget = QtWidgets.QWidget(PolarGraphs)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 70, 821, 471))
        self.frame.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(20, 60, 471, 371))
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 8px;\n"
"border: 2px solid #000000;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setStyleSheet("QLabel {\n"
"border: none;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 5)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(520, 60, 281, 371))
        self.frame_3.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 8px;\n"
"border: 2px solid #000000;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_3)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 261, 351))
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 0px;\n"
"border: 1px solid #000000;\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 61, 51))
        self.pushButton.setStyleSheet("QPushButton{\n"
"image: url(:/icons/Iconos/abrir.png);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border: 2px solid #000000;\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 10, 61, 51))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"image: url(:/icons/Iconos/Agregar.png);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border: 2px solid #000000;\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 10, 61, 51))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    image: url(:/icons/Iconos/Guardar.png);\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border: 2px solid #000000;\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(220, 10, 61, 51))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    image: url(:/icons/Iconos/interpolar.png);\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border: 2px solid #000000;\n"
"}")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(290, 10, 61, 51))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    image: url(:/icons/Iconos/polar.png);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border: 2px solid #000000;\n"
"}")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(360, 10, 61, 51))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    image: url(:/icons/Iconos/Editar.png);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border: 2px solid #000000;\n"
"}")
        self.pushButton_6.setText("")
        self.pushButton_6.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(750, 10, 91, 51))
        self.label_2.setStyleSheet("image: url(:/icons/Iconos/cst.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 550, 281, 16))
        self.label_3.setObjectName("label_3")
        PolarGraphs.setCentralWidget(self.centralwidget)

        self.retranslateUi(PolarGraphs)
        QtCore.QMetaObject.connectSlotsByName(PolarGraphs)

    def retranslateUi(self, PolarGraphs):
        _translate = QtCore.QCoreApplication.translate
        PolarGraphs.setWindowTitle(_translate("PolarGraphs", "MainWindow"))
        self.label.setText(_translate("PolarGraphs", "GRAFICA POLAR"))
        self.pushButton.setToolTip(_translate("PolarGraphs", "<html><head/><body><p>Open</p></body></html>"))
        self.pushButton_2.setToolTip(_translate("PolarGraphs", "<html><head/><body><p>New plot</p></body></html>"))
        self.pushButton_3.setToolTip(_translate("PolarGraphs", "<html><head/><body><p>Save</p></body></html>"))
        self.pushButton_4.setToolTip(_translate("PolarGraphs", "<html><head/><body><p>Interpolate</p></body></html>"))
        self.pushButton_5.setToolTip(_translate("PolarGraphs", "<html><head/><body><p>Polar plot</p></body></html>"))
        self.pushButton_6.setToolTip(_translate("PolarGraphs", "<html><head/><body><p>Edit</p></body></html>"))
        self.label_3.setText(_translate("PolarGraphs", "by Juan Carlos Morales - Telecommunications Engineer"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PolarGraphs = QtWidgets.QMainWindow()
    ui = Ui_PolarGraphs()
    ui.setupUi(PolarGraphs)
    PolarGraphs.show()
    sys.exit(app.exec_())
